flowchart TD
  1(check user account) -->|ok| 2
  2(query edition items<br/> with ISBN<br/>but no K10plus PPN) --> loop
  subgraph loop[for each QID,ISBN]
    A(ISBN already looked up?) --> |no| B(look up ISBN in K10plus)
    B --> C(exactely one PPN found?)
    C -->|yes| D(item QID already has K10Plus PPN?)
    D -->|no| E(Add claim with PPN to QID)
  end
